basePath: /
definitions:
  ecommerce_api-gateway_internal_dto.ErrorResponse:
    properties:
      message:
        example: Error description goes here
        type: string
      success:
        example: false
        type: boolean
    type: object
  ecommerce_api-gateway_internal_dto.IDData:
    properties:
      id:
        example: 123
        type: integer
    type: object
  ecommerce_api-gateway_internal_dto.IDResponse:
    properties:
      data:
        $ref: '#/definitions/ecommerce_api-gateway_internal_dto.IDData'
      message:
        example: Operation successful
        type: string
      success:
        example: true
        type: boolean
    type: object
  ecommerce_api-gateway_internal_dto.ProductData:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: Wireless Mouse
        type: string
      price:
        example: 49.99
        type: number
    type: object
  ecommerce_api-gateway_internal_dto.ProductListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ProductData'
        type: array
      message:
        example: Products retrieved successfully
        type: string
      success:
        example: true
        type: boolean
    type: object
  ecommerce_api-gateway_internal_dto.ProductReq:
    properties:
      name:
        example: Wireless Mouse
        type: string
      price:
        example: 49.99
        type: number
    required:
    - name
    - price
    type: object
  ecommerce_api-gateway_internal_dto.ProductResponse:
    properties:
      data:
        $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ProductData'
      message:
        example: Product found
        type: string
      success:
        example: true
        type: boolean
    type: object
  internal_handler.AddStockReq:
    properties:
      product_id:
        example: 1
        type: integer
      quantity:
        example: 50
        type: integer
    type: object
  internal_handler.CheckoutReq:
    properties:
      amount:
        example: 49.99
        type: number
      product_id:
        example: 1
        type: integer
    type: object
  internal_handler.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_handler.RegisterReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_handler.UpdateProfileReq:
    properties:
      address:
        type: string
      full_name:
        type: string
      phone:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Gateway for the Go gRPC E-Commerce system.
  title: E-Commerce Microservices API
  version: "1.0"
paths:
  /api/checkout:
    post:
      consumes:
      - application/json
      description: Initiates the Saga pattern for ordering a product
      parameters:
      - description: Checkout Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.CheckoutReq'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create an Order (Checkout)
      tags:
      - Orders
  /api/inventory/{id}:
    get:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get Product Stock
      tags:
      - Inventory
  /api/inventory/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Stock Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.AddStockReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Add Physical Stock
      tags:
      - Inventory
  /api/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login user
      tags:
      - Users
  /api/orders/{id}:
    get:
      description: Check if an order is PENDING, COMPLETED, or CANCELLED
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get Order Status
      tags:
      - Orders
  /api/payments/{order_id}:
    get:
      description: Check the raw transaction status from the payment gateway
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get Payment Status
      tags:
      - Payments
  /api/products:
    get:
      description: Retrieves all products from the catalog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ProductListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
      summary: List all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Adds a new product to the catalog and publishes to Kafka
      parameters:
      - description: Product Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ProductReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.IDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
      summary: Create a new product
      tags:
      - Products
  /api/products/{id}:
    delete:
      description: Removes a product from the catalog
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.IDResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
      summary: Delete a product
      tags:
      - Products
    get:
      description: Fetches a single product's details
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ProductResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
      summary: Get a product by ID
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Updates an existing product's name and price
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Product Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ProductReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.IDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ecommerce_api-gateway_internal_dto.ErrorResponse'
      summary: Update a product
      tags:
      - Products
  /api/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.RegisterReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - Users
  /api/search:
    get:
      description: Query the Elasticsearch cluster for products matching the search
        term
      parameters:
      - description: Search term (e.g., 'mouse')
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: Search products
      tags:
      - Search
  /api/users/profile:
    put:
      consumes:
      - application/json
      parameters:
      - description: Profile Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UpdateProfileReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update User Profile
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
